apiVersion: v1
kind: Service
metadata:
  name: abc-tech-service
spec:
  selector:
    app: abc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30004
  type: NodePort
